# Generated by Django 5.2.7 on 2026-01-17 19:46

import django.core.validators
import utils.paths
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address already exists.'}, help_text='Required. Unique. Must be a valid and unique email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Required. 15 characters or fewer. Letters only.', max_length=15, validators=[utils.validators.NameValidator('First Name')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, help_text='Allowed formats: png, jpg, jpeg, gif.', null=True, upload_to=utils.paths.get_user_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Required. 15 characters or fewer. Letters only.', max_length=15, validators=[utils.validators.NameValidator('Last Name')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'This phone number already exists.'}, help_text='Required. Unique. 15 characters or fewer.', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username already exists.'}, help_text='Required. Unique. 30 characters or fewer. Lowercase letters, numbers, dot and underline only.', max_length=30, unique=True, validators=[utils.validators.UsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True, help_text='100 characters or fewer. Must starts with https://', max_length=100, null=True, validators=[utils.validators.URLValidator()]),
        ),
    ]
