# Generated by Django 5.2.7 on 2026-01-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('post', 'Post'), ('comment', 'Comment'), ('like', 'Like'), ('Story', 'story')], max_length=20),
        ),
    ]
