# Generated by Django 5.2.7 on 2026-01-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('post', 'Post'), ('comment', 'Comment'), ('like', 'Like'), ('story', 'Story')], max_length=20),
        ),
    ]
